# config/sidekiq.yml

:scheduler:
  :schedule:
    pull_pool_info_job:
      cron: '*/10 * * * *' # Runs every 10 minutes
      class: PullPoolInfoJob
    pull_hr_job:
      cron: '0 * * * * *' # Runs once per minute
      class: PullHrJob
    pull_worker_info_job:
      cron: '0 * * * * *' # Runs once per minute
      class: PullWorkerInfoJob
    chart_data_cleanup:
      cron: '0 0 * * *' # Runs at midnight (00:00) every day
      class: ChartDataCleanupWorker
